name: Setup and Test

on:
  # Manual trigger only
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Test YouTube connection
      - name: Test YouTube API Connection
        env:
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Testing connections..."
          python src/youtube_monitor.py --test
      
      # Display configuration info
      - name: Display Configuration
        run: |
          echo "=== Configuration Summary ==="
          echo "Python version: $(python --version)"
          echo "Installed packages:"
          pip list
          echo ""
          echo "Repository structure:"
          find . -type f -name "*.py" | grep -v __pycache__ | sort
          echo ""
          echo "=== Setup Complete ==="
          echo "If all tests passed, your YouTube Subscription Monitor is ready!"
          echo "The monitor will run automatically every 30 minutes."
          echo "You can also trigger it manually from the Actions tab."
